SELECT
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLAE,
    COLUMN_KEY,
    COLUMN_DEFAULT,
    EXTRA
FROM 
    INFORMATION_SCHEMA.COLUMNS
WHERE
    TABLE_SCHEMA = 'alx_book_store.sql'
    AND TABLE_NAME = 'books'